[context]
path = "code"

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["cd code && npm install"]

[phases.build]
cmds = ["cd code && npm run build"]

[start]
cmd = "cd code && npx serve -s dist" 